mybatis:
  type-aliases-package: com.study.springvueapiboard.backend.dtos
  configuration:
    map-underscore-to-camel-case: true
    level:
      com.study.springboard.repository: trace
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebrainsoft_study
    username: ebsoft
    password: ebsoft
